// <auto-generated />
using System;
using FPTBook.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FPTBook.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FPTBook.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("FPTBook.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Page")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Publisher")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Manh Tung",
                            CategoryId = 3,
                            Description = "dexplosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment",
                            Image = "sth.png",
                            Page = 99,
                            Price = 199.0,
                            Publisher = "Manh Tung",
                            Quantity = 5,
                            Title = "How to have megakill",
                            Year = 2022
                        },
                        new
                        {
                            Id = 2,
                            Author = "Manh Tung",
                            CategoryId = 2,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "st.png",
                            Page = 49,
                            Price = 195.0,
                            Publisher = "Manh Tung",
                            Quantity = 10,
                            Title = "How to defeat",
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            Author = "Manh Tung",
                            CategoryId = 1,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "sth.png",
                            Page = 49,
                            Price = 195.0,
                            Publisher = "Manh Tung",
                            Quantity = 10,
                            Title = "You are mine",
                            Year = 2019
                        },
                        new
                        {
                            Id = 4,
                            Author = "Eichiro Oda",
                            CategoryId = 2,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "op1.jpg",
                            Page = 200,
                            Price = 2.1899999999999999,
                            Publisher = "Eichiro Oda",
                            Quantity = 15,
                            Title = "One piece vol 1",
                            Year = 1997
                        },
                        new
                        {
                            Id = 5,
                            Author = "Eichiro Oda",
                            CategoryId = 2,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "op2.jpg",
                            Page = 200,
                            Price = 2.9900000000000002,
                            Publisher = "Eichiro Oda",
                            Quantity = 15,
                            Title = "One piece vol 10",
                            Year = 1998
                        },
                        new
                        {
                            Id = 6,
                            Author = "Eichiro Oda",
                            CategoryId = 2,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "op3.jpg",
                            Page = 200,
                            Price = 2.0899999999999999,
                            Publisher = "Eichiro Oda",
                            Quantity = 15,
                            Title = "One piece vol 15",
                            Year = 1999
                        },
                        new
                        {
                            Id = 7,
                            Author = "Eichiro Oda",
                            CategoryId = 2,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "op4.jpg",
                            Page = 200,
                            Price = 1.99,
                            Publisher = "Eichiro Oda",
                            Quantity = 7,
                            Title = "One piece vol 16",
                            Year = 1999
                        },
                        new
                        {
                            Id = 8,
                            Author = "Eichiro Oda",
                            CategoryId = 2,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "op5.jpg",
                            Page = 200,
                            Price = 2.1899999999999999,
                            Publisher = "Eichiro Oda",
                            Quantity = 5,
                            Title = "One piece vol 21",
                            Year = 1999
                        },
                        new
                        {
                            Id = 9,
                            Author = "Eichiro Oda",
                            CategoryId = 2,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "op6.jpg",
                            Page = 200,
                            Price = 2.1899999999999999,
                            Publisher = "Eichiro Oda",
                            Quantity = 10,
                            Title = "One piece vol 25",
                            Year = 1999
                        },
                        new
                        {
                            Id = 10,
                            Author = "Manh Tung",
                            CategoryId = 1,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "hor1.jpg",
                            Page = 500,
                            Price = 197.0,
                            Publisher = "Manh Tung",
                            Quantity = 1,
                            Title = "Horro1",
                            Year = 2018
                        },
                        new
                        {
                            Id = 11,
                            Author = "Manh Tung",
                            CategoryId = 1,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "hor2.jpg",
                            Page = 10,
                            Price = 149.0,
                            Publisher = "Manh Tung",
                            Quantity = 9,
                            Title = "Monday is tomorrow vol 1",
                            Year = 2020
                        },
                        new
                        {
                            Id = 12,
                            Author = "Joker",
                            CategoryId = 1,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "hor3.jpg",
                            Page = 10,
                            Price = 159.0,
                            Publisher = "Joker",
                            Quantity = 9,
                            Title = "Monday is tomorrow vol 2",
                            Year = 2020
                        },
                        new
                        {
                            Id = 13,
                            Author = "Vladimir Putin",
                            CategoryId = 1,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "hor4.jpg",
                            Page = 10,
                            Price = 169.0,
                            Publisher = "Manh Tung",
                            Quantity = 10,
                            Title = "Monday is tomorrow vol 3",
                            Year = 2021
                        },
                        new
                        {
                            Id = 14,
                            Author = "Vladimir Putin",
                            CategoryId = 1,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "hor5.jpg",
                            Page = 10,
                            Price = 169.0,
                            Publisher = "Manh Tung",
                            Quantity = 10,
                            Title = "Monday is tomorrow vol 4",
                            Year = 2022
                        },
                        new
                        {
                            Id = 15,
                            Author = "Vladimir Putin",
                            CategoryId = 1,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "hor6.jpg",
                            Page = 10,
                            Price = 99.0,
                            Publisher = "Vladimir Putin",
                            Quantity = 10,
                            Title = "Monday is tomorrow vol 5",
                            Year = 2022
                        },
                        new
                        {
                            Id = 16,
                            Author = "Edison",
                            CategoryId = 3,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "sc1.webp",
                            Page = 10,
                            Price = 599.0,
                            Publisher = "Edison",
                            Quantity = 100,
                            Title = "Be who you want",
                            Year = 1950
                        },
                        new
                        {
                            Id = 17,
                            Author = "Edison second",
                            CategoryId = 3,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "sc2.webp",
                            Page = 10,
                            Price = 5999.0,
                            Publisher = "Edison",
                            Quantity = 100,
                            Title = "Beeeeeeeeeee",
                            Year = 1951
                        },
                        new
                        {
                            Id = 18,
                            Author = "PDPT",
                            CategoryId = 3,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "sc8.webp",
                            Page = 100,
                            Price = 59.0,
                            Publisher = "Trog non",
                            Quantity = 5,
                            Title = "Hand made",
                            Year = 2002
                        },
                        new
                        {
                            Id = 19,
                            Author = "Geoper",
                            CategoryId = 3,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "sc3.webp",
                            Page = 299,
                            Price = 29.600000000000001,
                            Publisher = "Geoper",
                            Quantity = 19,
                            Title = "Geopedia",
                            Year = 1991
                        },
                        new
                        {
                            Id = 21,
                            Author = "Sciencer",
                            CategoryId = 3,
                            Description = @"In the era of economic development, digital transformation is taking place rapidly, the demand for energy use and storage is enormous. Therefore, the use of power storage devices to be able to
charge electrical devices is a lot. Batteries are an incredibly efficient storage tool that can be reused over and over again. With the explosion of electric cars today, the use of electric cars is a solution to replace cars using gasoline fuels to limit gas emissions into the environment. However, when used a lot, it will lead to battery bottles, reducing the storage capacity of the battery. Currently, people are faced with the elimination of a large number of electric vehicle batteries. Thereby, increasing the amount of batteries discharged into the environment, causing great environmental pollution. As a member of the research and development department, I was assigned a small project to explore solutions to the impact of digital terminals and how to reduce their impact on the environment or functionality. potential to refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "sc4.webp",
                            Page = 1093,
                            Price = 225.19999999999999,
                            Publisher = "Sciencer",
                            Quantity = 3,
                            Title = "The sience of can and can't ",
                            Year = 1997
                        },
                        new
                        {
                            Id = 20,
                            Author = "zhongli",
                            CategoryId = 3,
                            Description = "In the era offficlectr e of the refurbish, repair and reuse digital devices instead of replacing them. And the main topic that I will talk about in this report is ",
                            Image = "sc11.webp",
                            Page = 999,
                            Price = 9999.0,
                            Publisher = "Manh Tung",
                            Quantity = 3,
                            Title = "Shape history",
                            Year = 2004
                        });
                });

            modelBuilder.Entity("FPTBook.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "18+",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 2,
                            Description = "12+",
                            Name = "Manga"
                        },
                        new
                        {
                            Id = 3,
                            Description = "everyone",
                            Name = "Science"
                        });
                });

            modelBuilder.Entity("FPTBook.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Item_Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.Property<int?>("bookId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("bookId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("FPTBook.Models.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "admin",
                            ConcurrencyStamp = "a0dc88cc-e21c-4499-ab21-0f4bc2a4aa24",
                            Name = "Administrator",
                            NormalizedName = "Administrator"
                        },
                        new
                        {
                            Id = "customer",
                            ConcurrencyStamp = "b1d46d99-a208-49d1-8142-79cb04c4af18",
                            Name = "Customer",
                            NormalizedName = "Customer"
                        },
                        new
                        {
                            Id = "storeOwner",
                            ConcurrencyStamp = "28f8dc3a-ddad-4ce4-a121-aa1dc1c403b3",
                            Name = "StoreOwner",
                            NormalizedName = "StoreOwner"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "52557ff0-aaa9-4827-8127-fea61990e5b2",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "admin@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEKWG/rI9ooB9pASBMIeys5qp1tq1i+EmEzsm4SIioGbzjRXYZ03QAFi/r8OLUkgg/A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a8fa5825-1dbb-4be9-9057-550b71dc9b22",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "80a2ce3e-5799-4482-bdfc-0e7fc5009a5f",
                            Email = "customer@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "customer@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEIBOB/lFBywf2KKvJ6cwxoxaz05apcEcw/0iJ4dL69osoF0a/zwyWurQZzIBWMs4Rg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10e2babd-74a0-43e2-8577-250c59cd3b99",
                            TwoFactorEnabled = false,
                            UserName = "customer@gmail.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f8610140-4a93-481e-b9aa-4be16af0279a",
                            Email = "storeOwner@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "storeOwner@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEAKeImludGimOWbzqmKa7T8bPqm7HElkTb++mVfCOfeyQ+/sh4Z+fKCXk6yYIzAisQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5e77c9ba-2aa7-4eb4-8a4a-d12319e24521",
                            TwoFactorEnabled = false,
                            UserName = "storeOwner@gmail.com"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe99cd57-dcbb-4838-a290-034a0f69b543",
                            Email = "customer2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "customer2@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEDXjE8WXqChaYQDZeONBkUGIgno+x0n6YgZF1tRPlqOPYEt0hhNCzW8qZ4LkfJ5Ofg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "32e28eb8-e737-4267-9025-5a78aada5ff0",
                            TwoFactorEnabled = false,
                            UserName = "customer2@gmail.com"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43fecadc-c81c-43ea-baed-b2042c644ee0",
                            Email = "storeOwner2@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "storeOwner2@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEP+aO1K+65kasdPjcNLfJK8Vc5HfiZvSG6vnGHHuu6enm5cNTQDIPAv77IbbkmD8OQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a6fd7df1-363c-4e8d-83b1-837e1d0aa733",
                            TwoFactorEnabled = false,
                            UserName = "storeOwner2@gmail.com"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4c4f4ba1-fc6d-4908-aae0-e1cfea5bde3c",
                            Email = "customer3@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "customer3@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEDZO8QBvCAz64xX0Fbi77XuBx2sd+eJYqT2w/dwprUpjA8cJypXzVDawyO7+ADZrYg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6cae41dd-a23a-4ab5-9285-7a38d6ef4fdf",
                            TwoFactorEnabled = false,
                            UserName = "customer3@gmail.com"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "af15250a-ad48-4df3-8f23-6f969bf770e5",
                            Email = "storeOwner3@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "storeOwner3@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEEd4G5pPADANL1rqUTubKdI2naKSoWxCBszYbDkeX0H7pemnxKVB6mSv6sbTzFzZJg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a5ba2d56-fd6e-4f28-8703-1345ec3b5215",
                            TwoFactorEnabled = false,
                            UserName = "storeOwner3@gmail.com"
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a88bf748-51c2-4874-be9e-e5efc249f719",
                            Email = "customer4@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "customer4@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEAXHCas3e7MJWv65deezuco0Hxamx3L0E2J7KnYBcS/TMAz3ayPR6Wopcu3xhzctqQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "6a60c127-20ac-4a36-abac-67203bd9a5eb",
                            TwoFactorEnabled = false,
                            UserName = "customer4@gmail.com"
                        },
                        new
                        {
                            Id = "9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1320d58e-89ec-4a49-b292-87c5f58c5826",
                            Email = "storeOwner4@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "storeOwner4@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEIqajVr27XCnNhLu5iT83Psz4AgRUz3IOpL6fpmHamXrKER0S7pqihyppe5WJt3S8A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "91036281-19aa-4be8-9efa-9b80d175ddbc",
                            TwoFactorEnabled = false,
                            UserName = "storeOwner4@gmail.com"
                        },
                        new
                        {
                            Id = "10",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "73873750-d4e0-4d73-8684-6a7221d58344",
                            Email = "customer5@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "customer5@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEE0bd5bc815ruUTOJxseDxxswyjXICE0VDbDyLwvV7oh9SXVnKwhVR7Jgk/Bz1Flqw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ae84311f-1b15-4200-ab01-1d79fb50c497",
                            TwoFactorEnabled = false,
                            UserName = "customer5@gmail.com"
                        },
                        new
                        {
                            Id = "11",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c73afb9-cda2-4c93-a8d1-5e1d8224e9ab",
                            Email = "storeOwner5@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedUserName = "storeOwner5@gmail.com",
                            PasswordHash = "AQAAAAEAACcQAAAAECl90ZL1AkOafqHXpN0xxKK3ynXDnPh8y1epF0Ifu9P9eQ/BaVGe0t7tSve/SNMpxw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8bb749da-e908-4074-b7fb-2e8a026702c0",
                            TwoFactorEnabled = false,
                            UserName = "storeOwner5@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "admin"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "customer"
                        },
                        new
                        {
                            UserId = "4",
                            RoleId = "customer"
                        },
                        new
                        {
                            UserId = "6",
                            RoleId = "customer"
                        },
                        new
                        {
                            UserId = "8",
                            RoleId = "customer"
                        },
                        new
                        {
                            UserId = "10",
                            RoleId = "customer"
                        },
                        new
                        {
                            UserId = "5",
                            RoleId = "storeOwner"
                        },
                        new
                        {
                            UserId = "7",
                            RoleId = "storeOwner"
                        },
                        new
                        {
                            UserId = "9",
                            RoleId = "storeOwner"
                        },
                        new
                        {
                            UserId = "11",
                            RoleId = "storeOwner"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("FPTBook.Models.Bill", b =>
                {
                    b.HasOne("FPTBook.Models.Book", "Book")
                        .WithMany("Bills")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FPTBook.Models.Book", b =>
                {
                    b.HasOne("FPTBook.Models.Category", "Category")
                        .WithMany("books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FPTBook.Models.Item", b =>
                {
                    b.HasOne("FPTBook.Models.Book", "book")
                        .WithMany()
                        .HasForeignKey("bookId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
